version: '3'

services:
  web:
    build: .
    container_name: webshop
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/Main
    ports:
      - "8000:8000"
    networks:
      - app-network  
volumes:
  postgres_data:

networks:
  app-network:  
    driver: bridge  

