version: '3'

services:

  web_database:
    image: postgres:latest
    container_name: fashion_database
    environment:
      POSTGRES_DB: fashion_shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    
  web:
    build: .
    container_name: webshop
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/Main
    ports:
      - "8000:8000"
    depends_on:
      - web_database      


volumes:
  postgres_data:


