# Generated by Django 5.0 on 2024-01-01 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userprofile_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='wallet',
        ),
    ]
