# Generated by Django 5.0 on 2024-01-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcart',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
