# Generated by Django 5.0 on 2024-01-03 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_shopcart_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopcart',
            old_name='name',
            new_name='size',
        ),
    ]
