# Generated by Django 5.0 on 2024-01-05 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_name_shopcart_size'),
        ('user', '0002_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcart',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.coupon'),
        ),
    ]
