# Generated by Django 5.0 on 2023-12-31 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_payment_orderproduct_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcart',
            name='order_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopcart',
            name='single_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
