# Generated by Django 5.0 on 2024-01-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_shopcart_coupon_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='size',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
