# Generated by Django 5.0 on 2024-02-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_wishlist_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_note',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
