# Generated by Django 5.0 on 2024-02-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_user_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund',
            field=models.BooleanField(default=False),
        ),
    ]
